
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable Node.js version

      - name: Install dependencies
        # Changed from 'npm ci' to 'npm install' to ensure package-lock.json is generated if missing
        run: npm install

      - name: Build React app
        run: npm run build # This runs the 'build' script defined in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # The directory containing your built static files
          publish_branch: gh-pages # The branch where the static content will be published
